# Generated by Django 2.2.3 on 2019-07-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage_playlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwebpage',
            name='user_html',
            field=models.FileField(upload_to=''),
        ),
    ]
