# Generated by Django 2.2.3 on 2019-07-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage_playlist', '0002_auto_20190718_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwebpage',
            name='user_html',
            field=models.FileField(upload_to='media/'),
        ),
    ]
